let n1 = 10;
let n2 = 20;
let suma = n1 + n2;
let resta = n1 - n2;
let multiplicacion = n1 * n2 ;
let division = n1 / n2;
console.log (suma);
console.log (resta);
console.log (multiplicacion);
console.log (division);